import React from 'react';
import { createRoot } from 'react-dom/client';
import { motion, MotionConfig, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, Check, ChevronDown, CircleCheck, Clock3, CreditCard, Eye, Fingerprint, Globe2, LockKeyhole, Menu, Plus, ReceiptText, Send, ShieldCheck, Sparkles, UserRound, WalletCards, X, Zap } from 'lucide-react';
import './styles.css';
import './motion.css';
import './responsive.css';
import { WaitlistModal } from './waitlist';
import { Logo } from './logo';

const A='/signup';
function Reveal({children,className=''}:{children:React.ReactNode,className?:string}) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={reduced ? false : {opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.7,ease:[.22,1,.36,1]}}>{children}</motion.div>;
}

function MotionDirector() {
  React.useEffect(() => {
    const targets = document.querySelectorAll<HTMLElement>('.feature,.step,.dashboard,.split,.security-wrap,.quote,.hero-visual');
    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        entry.target.classList.toggle('motion-visible', entry.isIntersecting);
        if(entry.isIntersecting) entry.target.classList.add('motion-entered');
      });
    }, {threshold:.15});
    targets.forEach((target) => observer.observe(target));
    const product = document.querySelector('.product');
    if(product) product.id = 'product';
    return () => observer.disconnect();
  }, []);
  return null;
}
const Btn=({children,light=false,arrow=true,href=A}:{children:React.ReactNode,light?:boolean,arrow?:boolean,href?:string})=><a href={href} className={`btn ${light?'light':''}`}>{children}{arrow&&<ArrowUpRight size={17}/>}</a>;

function Navbar(){
  const [open,setOpen]=React.useState(false);
  const [waitlistOpen,setWaitlistOpen]=React.useState(false);
  const [scrolled,setScrolled]=React.useState(false);
  const toggle=React.useRef<HTMLButtonElement>(null);
  const nav=React.useRef<HTMLElement>(null);
  React.useEffect(()=>{
    const onScroll=()=>setScrolled(window.scrollY>18);
    const onResize=()=>{if(window.innerWidth>900)setOpen(false)};
    onScroll();window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onResize);
    return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onResize)};
  },[]);
  React.useEffect(()=>{
    if(!open)return;
    const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);toggle.current?.focus()}};
    const outside=(event:PointerEvent)=>{if(!nav.current?.contains(event.target as Node))setOpen(false)};
    window.addEventListener('keydown',close);window.addEventListener('pointerdown',outside);
    return()=>{window.removeEventListener('keydown',close);window.removeEventListener('pointerdown',outside)};
  },[open]);
  return <><nav ref={nav} aria-label="Main navigation" className={`${scrolled?'scrolled':''} ${open?'menu-open':''}`} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))setOpen(false)}}>
    <div onClick={()=>setOpen(false)}><Logo/></div>
    <div id="main-navigation" className={`navlinks ${open?'open':''}`} onClick={event=>{if((event.target as HTMLElement).closest('a'))setOpen(false)}}>
      <a href="#features">Features</a><a href="#works">How it works</a><a href="#security">Security</a><a href="#faq">FAQs</a><button type="button" className="btn" aria-haspopup="dialog" onClick={()=>{setOpen(false);setWaitlistOpen(true)}}>Join the waitlist <ArrowUpRight size={17}/></button>
    </div>
    <button ref={toggle} className="menu" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-controls="main-navigation" aria-label={open?'Close navigation':'Open navigation'}>{open?<X/>:<Menu/>}</button>
  </nav><WaitlistModal open={waitlistOpen} onClose={()=>{setWaitlistOpen(false);if(window.innerWidth<=900)toggle.current?.focus()}}/></>;
}

function SendCard(){return <div className="send-card"><div className="card-top"><button>←</button><b>Send money</b><span>•••</span></div><div className="recipient"><span className="avatar">JD</span><div><small>Sending to</small><strong>John Doe</strong></div><CircleCheck size={20}/></div><small className="center">Enter amount</small><div className="amount"><sup>₦</sup>50,000<span>.00</span></div><div className="available"><span>Available balance</span><b>₦245,800</b></div><button className="confirm">Continue <ArrowRight size={17}/></button></div>}

function Hero(){return <header id="top" className="hero"><Navbar/><div className="hero-grid"><Reveal className="hero-copy"><div className="eyebrow"><i></i> The money app built for real life</div><h1>Your money.<br/><em>Ready to move.</em></h1><p>One simple app to send, receive, and stay in control of your money—without the usual friction.</p><div className="actions"><Btn>Open an account</Btn><a className="text-link" href="#product">Explore the app <ArrowRight size={16}/></a></div><div className="app-proof"><div className="proof-avatars"><span>DA</span><span>SO</span><span>MO</span></div><p><b>Simple from the first tap.</b><small>Fast transfers · Clear tracking · Built securely</small></p></div></Reveal><Reveal className="hero-visual"><div className="hero-word">MOVE</div><div className="lime-disc"></div><div className="phone app-phone"><div className="app-status"><span>9:41</span><i></i><b>● ●</b></div><div className="home-top"><div><small>Good morning, Alex</small><b>Your money</b></div><span>AD</span></div><div className="home-balance"><small>Available balance <Eye size={13}/></small><strong>₦245,800<span>.00</span></strong><em>+₦50,000 this month</em></div><div className="quick-actions"><button><span><Send/></span>Send</button><button><span><ArrowDownIcon/></span>Receive</button><button><span><Plus/></span>Add money</button></div><div className="home-activity"><div><b>Recent activity</b><small>See all</small></div><div className="home-tx"><span>SO</span><p><b>Sarah O.</b><small>Money received</small></p><strong>+₦50,000</strong></div><div className="home-tx"><span>MO</span><p><b>Michael O.</b><small>Transfer sent</small></p><strong className="debit">−₦20,000</strong></div></div></div><motion.div className="received" animate={{y:[0,-8,0]}} transition={{duration:4,repeat:Infinity}}><span><ArrowDownIcon/></span><div><small>Money received</small><b>+ ₦50,000.00</b></div><strong>now</strong></motion.div><div className="secure-chip"><ShieldCheck/> Your transfer is protected</div><div className="tap-chip"><Zap/> Sent in seconds</div></Reveal></div><div className="hero-bottom"><span>Send money</span><i></i><span>Receive money</span><i></i><span>Track every naira</span></div></header>}
const ArrowDownIcon=()=> <ArrowRight size={19} style={{transform:'rotate(135deg)'}}/>;

const features=[{n:'01',icon:<Send/>,title:'Send in seconds',text:'Send money to the people who matter, without the unnecessary steps.',visual:<div className="mini-send"><span>SD</span><div><small>Sarah Daniel</small><b>₦20,000</b></div><ArrowRight/></div>},{n:'02',icon:<WalletCards/>,title:'Receive with ease',text:'Get paid directly into your Linmoni account and see it instantly.',visual:<div className="mini-alert"><CircleCheck/><div><b>Payment received</b><small>+ ₦85,000.00</small></div></div>},{n:'03',icon:<Zap/>,title:'Made to move fast',text:'A clear, confident flow gets your money where it needs to go.',visual:<div className="flow"><span>You</span><i></i><b>L</b><i></i><span>Them</span></div>},{n:'04',icon:<Fingerprint/>,title:'Secure by design',text:'Modern safeguards help protect your account and every transaction.',visual:<div className="secure-visual"><Fingerprint/><span>Identity verified</span><Check/></div>}];
function Features(){return <section id="features" className="section"><Reveal className="section-head"><span className="label">Built for everyday money</span><h2>Everything you need<br/>to move money.</h2><p>From quick transfers to instant visibility, Linmoni gives you a simpler way to stay in control.</p></Reveal><div className="feature-grid">{features.map((f,i)=><Reveal className={`feature f${i}`} key={f.title}><div className="feature-meta"><span>{f.icon}</span><small>{f.n}</small></div><h3>{f.title}</h3><p>{f.text}</p>{f.visual}</Reveal>)}</div></section>}
function TrustStrip(){return <div className="trust-strip"><span>Built for simple, secure money movement</span><div><b><LockKeyhole/> Secure</b><b><Zap/> Fast</b><b><CreditCard/> Easy</b><b><Globe2/> Accessible</b></div></div>}
function How(){return <section id="works" className="how section"><Reveal className="section-head row"><div><span className="label">How it works</span><h2>Money movement,<br/>simplified.</h2></div><p>Three simple steps. No unnecessary complexity between you and the people that matter.</p></Reveal><div className="steps">{[['01','Create your account','Sign up and set up your Linmoni account in minutes.'],['02','Choose what to do','Send money or receive money from another person.'],['03','Complete the transfer','Confirm your transaction and you’re done.']].map((s,i)=><Reveal className="step" key={s[0]}><span>{s[0]}</span><div className="step-icon">{i===0?<UserRound/>:i===1?<Send/>:<Check/>}</div><h3>{s[1]}</h3><p>{s[2]}</p></Reveal>)}</div></section>}
function Dashboard(){return <div className="dashboard"><aside><Logo/><div className="side-links"><span className="active"><WalletCards/> Overview</span><span><Send/> Send money</span><span><ReceiptText/> Transactions</span><span><UserRound/> Account</span></div><div className="profile"><b>AD</b><span>Alex D.<small>Personal account</small></span></div></aside><main><div className="dash-top"><div><small>Welcome back, Alex</small><h3>Good morning.</h3></div><span><Clock3/></span></div><div className="balance"><div><small>Available balance <Eye/></small><strong>₦245,800<span>.00</span></strong><small>Last updated just now</small></div><div><button><Send/> Send</button><button><Plus/> Add money</button></div></div><div className="activity"><div className="activity-head"><b>Recent activity</b><span>See all <ArrowRight/></span></div>{[['S','Received from Sarah','Today, 10:42 AM','+₦50,000','in'],['M','Transfer to Michael','Yesterday, 4:15 PM','−₦20,000','out'],['D','Received from Daniel','Aug 28, 1:05 PM','+₦15,000','in']].map(t=><div className="tx" key={t[1]}><span>{t[0]}</span><div><b>{t[1]}</b><small>{t[2]}</small></div><strong className={t[4]}>{t[3]}</strong><i>Successful</i></div>)}</div></main></div>}
function Product(){return <section className="product"><Reveal className="product-head"><span className="label lime">Meet your new money space</span><h2>Your money.<br/><em>Your control.</em></h2><p>See your balance, move money, and keep track of every transaction—all from one clear, calm dashboard.</p></Reveal><Reveal><Dashboard/></Reveal></section>}

function SendReceive(){return <section className="section split-section"><Reveal className="split"><div className="split-copy"><span className="label">Send money</span><h2>There when you<br/>need to send.</h2><p>Whether you’re paying someone, helping family, or handling everyday expenses, Linmoni keeps it simple.</p><Btn>Send money</Btn></div><div className="mock-box send-bg"><SendCard/></div></Reveal><Reveal className="split reverse"><div className="split-copy"><span className="label">Receive money</span><h2>Get paid without<br/>the friction.</h2><p>Receive money directly through your Linmoni account. Clear, quick, and easy to track.</p><Btn>Receive money</Btn></div><div className="mock-box receive-bg"><div className="receive-card"><div className="receive-icon"><ArrowDownIcon/></div><span>Payment received</span><strong>₦50,000.00</strong><small>From Sarah O. • Just now</small><div><Check/> Money added to your balance</div></div></div></Reveal></section>}
function Security(){return <section id="security" className="security section"><div className="security-wrap"><Reveal className="security-art"><div className="rings"><div><ShieldCheck/></div></div><span className="protected"><Check/> Account protected</span><span className="monitored"><Eye/> 24/7 monitoring</span></Reveal><Reveal className="security-copy"><span className="label">Security at the core</span><h2>Your money deserves serious protection.</h2><p>Linmoni is designed with thoughtful safeguards that help keep your account and transactions protected.</p><div className="security-list">{['Secure authentication','Transaction protection','Account monitoring','Encrypted data','Fraud prevention'].map(x=><span key={x}><Check/> {x}</span>)}</div></Reveal></div></section>}
function Compare(){return <section className="section compare"><Reveal className="section-head"><span className="label">The Linmoni difference</span><h2>Why make money harder<br/>than it needs to be?</h2></Reveal><Reveal className="comparison"><div><small>The old way</small>{['Complicated processes','Too many steps','Slow experience','Poor visibility'].map(x=><p key={x}><X/> {x}</p>)}</div><div className="lin-way"><Logo/><b>A simpler way to move.</b>{['Simple experience','Fast transfers','Clear transaction history','Designed around you'].map(x=><p key={x}><Check/> {x}</p>)}</div></Reveal></section>}
const quotes=[['“Linmoni makes sending money ridiculously simple. I can send money and know exactly what’s happening.”','Daniel A.','DA'],['“Finally, a money app that doesn’t make every transaction feel complicated.”','Sarah O.','SO'],['“Clean, fast, and easy to understand. That’s exactly what I want from a financial app.”','Michael O.','MO']];
function Testimonials(){return <section className="testimonials section"><Reveal className="section-head row"><div><span className="label">Early community</span><h2>People are moving<br/>money differently.</h2></div><span className="quote-mark">“</span></Reveal><div className="quotes">{quotes.map(q=><Reveal className="quote" key={q[1]}><Sparkles/><p>{q[0]}</p><div><b>{q[2]}</b><span><strong>{q[1]}</strong><small>Linmoni user</small></span></div></Reveal>)}</div></section>}
const faqs=[['What is Linmoni?','Linmoni is a digital money platform that makes it simple to send, receive, and manage money.'],['How do I send money?','Choose a recipient, enter an amount, review the details, and confirm your transfer.'],['How do I receive money?','Your Linmoni account can receive money directly from other supported accounts.'],['How long do transfers take?','Most transfers are designed to complete quickly. Timing may vary by destination and payment network.'],['Is Linmoni secure?','Linmoni uses modern security practices including authentication, monitoring, and data protection.'],['Are there transaction fees?','Any applicable fee will always be shown clearly before you confirm a transaction.'],['How do I create an account?','Select Get started and follow the guided account setup process.'],['What happens if a transaction fails?','You’ll see a clear status and next steps. Funds from unsuccessful transfers are handled according to the payment channel used.']];
function FAQ(){const [active,setActive]=React.useState(0);return <section id="faq" className="faq section"><Reveal className="section-head"><span className="label">Need to know</span><h2>Frequently asked<br/>questions.</h2></Reveal><Reveal className="faq-list">{faqs.map((f,i)=><div className={`faq-item ${active===i?'active':''}`} key={f[0]}><button onClick={()=>setActive(active===i?-1:i)}><span>{f[0]}</span><ChevronDown/></button><div><p>{f[1]}</p></div></div>)}</Reveal></section>}
function Footer(){return <><section className="final"><Reveal><span className="label lime">Ready when you are</span><h2>Money should<br/>just <em>move.</em></h2><p>Send and receive money with a simpler experience built for the way you live today.</p><Btn light>Get started with Linmoni</Btn><small>No complicated setup. Just simple money movement.</small></Reveal><div className="orbit one"></div><div className="orbit two"></div></section><footer><div className="footer-brand"><Logo/><p>Simple, secure money movement.</p></div>{[['Product','Send money','Receive money','Features','Security'],['Company','About','Careers','Contact','Blog'],['Legal','Privacy','Terms','Security']].map(c=><div className="foot-col" key={c[0]}><b>{c[0]}</b>{c.slice(1).map(x=><a href="#" key={x}>{x}</a>)}</div>)}<div className="footer-bottom"><span>© 2026 Linmoni. All rights reserved.</span><div><a href="#">X</a><a href="#">Instagram</a><a href="#">LinkedIn</a></div></div></footer></>}
function App(){return <><Hero/><TrustStrip/><Features/><How/><Product/><SendReceive/><Security/><Compare/><Testimonials/><FAQ/><Footer/></>};
createRoot(document.getElementById('root')!).render(<React.StrictMode><MotionConfig reducedMotion="user"><App/><MotionDirector/></MotionConfig></React.StrictMode>);
